### ISSUE TITLE
Make it possible to pass multiple scenarioPaths to runScenario and run all of them in parallel

### ISSUE THREAD

**Issue by johannesloher** [MaibornWolff/alt-core-js#22]
Currently if we want to execute several different scenarios, we have two options:
- Place all of them in the same directory and pass the path to that directory to `runScenario`
- Execute `runScenario` for each single scenario.

The first solution allows us to execute the scenarios in parallel, but is quite restricted—we might not want to execute all of the scenarios in a given directory, but only some of them.

The second solution is more flexible in that it allows us to specify exactly which scenarios should be run, but in return we cannot run them in parallel.

In order to provide a flexible solution which also allows parallel execution of scenarios, we should adjust `runScenario` so that it takes an array of `scenarioPath`s instead of a single one, loads all of them and then executes them in parallel.

This is a breaking change. If we absolutely must avoid that, we could add `scenarioPaths?: Array<string>` as an optional last parameter to `runScenario` but I suggest that we simply accept that this is a breaking change.

Another option would be to to use the rest operator:
```ts
export const runScenario = (actionDir: string, outDir = 'out', envConfigFile: string, ...scenarioPaths: Array<string>) => {/* ... */ }
```
While this is also a breaking change, it is more flexible than the previous solution in that if we only want to run a single scenario, we do not have to wrap it in an array:

```ts
runScenario('/actionDir', '/outDir', '/envConfigFile', '/path/to/scenario.yaml'); // single scenario invocation
runScenario('/actionDir', '/outDir', '/envConfigFile', '/path/to/first/scenario.yaml', '/path/to/second/scenario.yaml'); // multiple scenario invocation
const scenarios = ['/path/to/first/scenario.yaml', '/path/to/second/scenario.yaml'];
runScenario('/actionDir', '/outDir', '/envConfigFile', ...scenarios); // multiple scenario invocation using array spreading
```

**Comment by bboron86** [comment]
@johannesloher how about second entrypoint named `runMultipleScenarios` which accepts an `Array<string>` and the client may choose which to use?

**Comment by johannesloher** [comment]
@bboron86 Sounds like a good plan to me 👍
