### ISSUE TITLE
Make it possible to run certain actions even though the scenario execution failed

### ISSUE THREAD

**Issue by bboron86** [MaibornWolff/alt-core-js#47]
It's common practice during a scenario run to create some context, run the business logic, and then delete the context at the end. If the scenario fails however, the context (e.g. registered users) remain in the system. 

It would be great to have the chance to declare an action as "always-runnable" and so to execute it event though the main scenario flow failed at some stage.

**Comment by bboron86** [comment]
see #48

**Comment by johannesloher** [comment]
@bboron86 If I am not mistaken, this is implemented with `invokeEvenOnFail` from #48, is that correct? If yes, let's close this issue.
