### ISSUE TITLE
Reusable Scenarios

### ISSUE THREAD

**Issue by bboron86** [MaibornWolff/alt-core-js#8]
Sometimes, multiple scenarios share same sequence of state-building-actions (create-test-user; activate-new-user; log-in). It would be great, if such sequences could be written down once and could be reused in multiple other scenarios => some sort of `import s1-log-in-user-scenario.yaml` would be desireable

**Comment by bboron86** [comment]
see #48

**Comment by johannesloher** [comment]
fixed by #48
